"""Creacion inicial de tablas

Revision ID: 01cf01c545bd
Revises: 
Create Date: 2026-02-09 18:52:45.864270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01cf01c545bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('es_premium', sa.Boolean(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('perfiles_empresas',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('ubicacion_sede', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('perfiles_estudiantes',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=255), nullable=True),
    sa.Column('institucion_educativa', sa.String(length=255), nullable=True),
    sa.Column('nivel_academico', sa.String(length=255), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('habilidades', sa.JSON(), nullable=True),
    sa.Column('cv_url', sa.String(length=255), nullable=True),
    sa.Column('cv_tipo_archivo', sa.String(length=255), nullable=True),
    sa.Column('foto_perfil_url', sa.String(length=255), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('modalidad_preferida', sa.Enum('remoto', 'presencial', 'hibrido', name='modalidad_estudiante'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('vacantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('tipo_contrato', sa.String(length=255), nullable=True),
    sa.Column('modalidad', sa.Enum('remoto', 'presencial', 'hibrido', name='modalidad_vacante'), nullable=True),
    sa.Column('ubicacion', sa.String(length=255), nullable=True),
    sa.Column('sueldo_minimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sueldo_maximo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.Enum('activa', 'pausada', 'cerrada', name='estado_vacante'), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['perfiles_empresas.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacantes_id'), 'vacantes', ['id'], unique=False)
    op.create_table('interacciones_swipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('vacante_id', sa.Integer(), nullable=True),
    sa.Column('interes_estudiante', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['perfiles_estudiantes.usuario_id'], ),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacciones_swipe_id'), 'interacciones_swipe', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estudiante_id', sa.Integer(), nullable=True),
    sa.Column('vacante_id', sa.Integer(), nullable=True),
    sa.Column('fecha_match', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['perfiles_estudiantes.usuario_id'], ),
    sa.ForeignKeyConstraint(['vacante_id'], ['vacantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('enviado', 'visto', 'en_proceso', 'rechazado', name='estado_postulacion'), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postulaciones_id'), 'postulaciones', ['id'], unique=False)
    op.create_table('retroalimentacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=True),
    sa.Column('campos_mejora', sa.Text(), nullable=True),
    sa.Column('sugerencias_perfil', sa.Text(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retroalimentacion_id'), 'retroalimentacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retroalimentacion_id'), table_name='retroalimentacion')
    op.drop_table('retroalimentacion')
    op.drop_index(op.f('ix_postulaciones_id'), table_name='postulaciones')
    op.drop_table('postulaciones')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_interacciones_swipe_id'), table_name='interacciones_swipe')
    op.drop_table('interacciones_swipe')
    op.drop_index(op.f('ix_vacantes_id'), table_name='vacantes')
    op.drop_table('vacantes')
    op.drop_table('perfiles_estudiantes')
    op.drop_table('perfiles_empresas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
