from app.models.user import User
from app.models.rol import Role
from app.models.perfil_estudiante import PerfilEstudiante
from app.models.perfil_empresa import PerfilEmpresa
from app.models.vacante import Vacante
from app.models.interaccion_swipe import InteraccionSwipe
from app.models.interaccion_swipe_empresa import InteraccionSwipeEmpresa
from app.models.vacante_visualizacion import VacanteVisualizacion
from app.models.match import Match
from app.models.postulacion import Postulacion
from app.models.retroalimentacion import Retroalimentacion
from app.models.plan import Plan
from app.models.suscripcion import Suscripcion
from app.models.notificacion import Notificacion
